version: "3.8"
name: ctf-liunx-nc

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wankkoree/ctf.linux.nc:1.0.0
    ports:
      - "10000:3000"
    environment:
      - FLAG=flag{12345678-abcd-1234-5678-abcdef123456}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 1
