version: "3.8"
name: ctf-sql-information_schema

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wankkoree/ctf.sql.information_schema:1.0.0
    ports:
      - "10000:80"
    environment:
      - FLAG=flag{12345678-abcd-1234-5678-abcdef123456}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 1
