name: build CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:
    name: 构建任务
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    permissions:
      packages: write
      contents: read
    steps:
      - name: 拉取仓库代码
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 构建 Docker 镜像
        id: build
        run: |
          find ~+ -type f -name 'docker-compose.yml' |
          while read -r docker_compose_path
          do
            cd $(dirname $docker_compose_path )
            docker compose build
          done

      - name: 登录 GitHub Packages Docker 镜像仓库
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 推送 Docker 镜像
        run: |
          docker images "wankkoree\/*" --format "{{.Repository}}:{{.Tag}}" | sed 's#wankkoree\/##' |
          while read -r docker_image
          do
            LOCAL_IMAGE=wankkoree/{docker_image}
            REMOTE_IMAGE_GHCR=ghcr.io/${{ github.repository_owner }}/${docker_image}
            docker tag ${LOCAL_IMAGE} ${REMOTE_IMAGE_GHCR}
            docker push ${REMOTE_IMAGE_GHCR}
          done
